language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

before_script:
  - g++ --version
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - g++ --version
  - dir
  - pwd
  - ls
  - g++ -c src/main.cpp -Iinclude -std=c++11 -Iusr/include
  - g++ -c src/Game2048.cpp -Iinclude -std=c++11 -Iusr/include
  - g++ -o main main.o Game2048.o -L./usr/lib -lsfml-system -lsfml-window -lsfml-graphics -std=c++11
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make