language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

before_script:
  - dir
  - pwd
  - ls
  - g++ -c src/main.cpp -Iinclude -std=c++14 -Iusr/include
  - g++ -c src/Game2048.cpp -Iinclude -std=c++14 -Iusr/include
  - g++ -o main main.o Game2048.o -L./usr/lib -lsfml-system -lsfml-window -lsfml-graphics -lfoo -std=c++14
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make