language: cpp

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

compiler:
  - gcc

before_script:
  - dir
  - pwd
  - ls
  - g++ -c src/main.cpp -Iinclude -std=c++11 -Iusr/include
  - g++ -c src/Game2048.cpp -Iinclude -std=c++11 -Iusr/include
  - g++ -o main main.o Game2048.o -L./usr/lib -lsfml-system -lsfml-window -lsfml-graphics -lfoo -std=c++14
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make